### ISSUE TITLE
refactor api-server to include /dates and /coordinates GET methods

### ISSUE THREAD

**Issue by mjstealey** [mjstealey/datatranslator#24]
Revised swagger definition to include
- [x] /exposures/{exposure_type}/coordinates
- [x] /exposures/{exposure_type}/dates

Reference: [environmental_exposures_api/1.0.0](https://app.swaggerhub.com/api/mjstealey/environmental_exposures_api/1.0.0)

**Comment by lstillwe** [comment]
Michael - was this requested?

**Comment by mjstealey** [comment]
> was this requested

@lstillwe - Requested by me :smile:

I should have it stubbed out in running by today's call.

Will make searching for valid coordinates and date ranges easier in the long run. And hopefully reduces the number of times we need to answer the questions about date ranges and valid points.

**Comment by lstillwe** [comment]
👍

**Comment by mjstealey** [comment]
merged
